--Trigger
--Chi tiết phiếu nhập
CREATE TRIGGER THEM_SLPN_TRIGGER ON CHI_TIET_PHIEU_NHAP AFTER INSERT AS
	BEGIN
		UPDATE LO_HANG
		SET SL = SL + (SELECT SL_NHAP FROM INSERTED WHERE MA_LO=LO_HANG.MA_LO)
		FROM LO_HANG
		JOIN INSERTED ON LO_HANG.MA_LO=INSERTED.MA_LO
	END
GO

CREATE TRIGGER SUA_SLPN_TRIGGER on CHI_TIET_PHIEU_NHAP after update AS
BEGIN
   UPDATE LO_HANG SET SL = SL +
	   (SELECT SL_NHAP FROM inserted WHERE MA_LO = LO_HANG.MA_LO) -
	   (SELECT SL_NHAP FROM deleted WHERE MA_LO = LO_HANG.MA_LO)
   FROM LO_HANG 
   JOIN deleted ON LO_HANG.MA_LO = deleted.MA_LO
end
GO

CREATE TRIGGER XOA_SLPN_TRIGGER on CHI_TIET_PHIEU_NHAP after delete AS
BEGIN
   UPDATE LO_HANG SET SL = SL -

	   (SELECT SL_NHAP FROM deleted WHERE MA_LO = LO_HANG.MA_LO)
   FROM LO_HANG 
   JOIN deleted ON LO_HANG.MA_LO = deleted.MA_LO
end
GO
--Chi tiết hóa đơn

CREATE TRIGGER THEM_SLHD_TRIGGER ON CHI_TIET_HOA_DON AFTER INSERT AS
	BEGIN
		UPDATE LO_HANG
		SET SL = SL - (SELECT SL_BAN FROM INSERTED WHERE MA_LO=LO_HANG.MA_LO)
		FROM LO_HANG
		JOIN INSERTED ON LO_HANG.MA_LO=INSERTED.MA_LO
	END
GO

CREATE TRIGGER SUA_SLHD_TRIGGER on CHI_TIET_HOA_DON after update AS
BEGIN
   UPDATE LO_HANG SET SL = SL -
	   (SELECT SL_BAN FROM inserted WHERE MA_LO = LO_HANG.MA_LO) +
	   (SELECT SL_BAN FROM deleted WHERE MA_LO = LO_HANG.MA_LO)
   FROM LO_HANG 
   JOIN deleted ON LO_HANG.MA_LO = deleted.MA_LO
end
GO

CREATE TRIGGER XOA_SLHD_TRIGGER ON CHI_TIET_HOA_DON FOR DELETE AS 
BEGIN
	UPDATE LO_HANG
	SET SL = SL + (SELECT SL_BAN FROM deleted WHERE MA_LO = LO_HANG.MA_LO)
	FROM LO_HANG 
	JOIN deleted ON LO_HANG.MA_LO = deleted.MA_LO
END
GO